import { LAST_UPDATED, LEGAL_CONTACTS, PRODUCT_NAME } from "@/lib/legal";

export const metadata = {
  title: `Disclaimer · ${PRODUCT_NAME}`,
  description: `Important disclaimers about the use of ${PRODUCT_NAME}.`,
};

export default function DisclaimerPage() {
  return (
    <article className="prose prose-slate max-w-none dark:prose-invert">
      <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
      <h1>Disclaimer</h1>
      <p>
        This disclaimer applies to {PRODUCT_NAME}, including its website, dashboard,
        and any related services. By using the service you accept the terms below.
      </p>

      <h2>1. General information</h2>
      <p>
        The information and content provided through {PRODUCT_NAME} is for general
        informational and operational purposes only. We make reasonable efforts to
        keep it accurate and up to date, but we make no warranties of any kind about
        its completeness, reliability, or suitability for any particular purpose.
      </p>

      <h2>2. AI-generated content</h2>
      <p>
        Some features may produce captions, replies, summaries, or recommendations
        generated by machine learning models. Such output is provided &quot;as is&quot; and may
        be inaccurate, incomplete, or inappropriate. You are responsible for reviewing
        AI-generated content before publishing or acting on it.
      </p>

      <h2>3. Third-party services</h2>
      <p>
        {PRODUCT_NAME} integrates with third-party platforms including Instagram
        (Meta). We are not affiliated with, endorsed by, or sponsored by those
        providers. Your use of any third-party service is governed by that
        provider&apos;s own terms. Outages, policy changes, or restrictions imposed
        by those providers may affect your use of our service.
      </p>

      <h2>4. No professional advice</h2>
      <p>
        Nothing on {PRODUCT_NAME} constitutes legal, financial, medical, or other
        professional advice. Do not rely on the service as a substitute for advice
        from a qualified professional.
      </p>

      <h2>5. Service availability</h2>
      <p>
        We aim for high availability, but we do not guarantee uninterrupted access.
        We may modify, suspend, or discontinue any feature at any time, with or
        without notice, in order to maintain, update, or improve the service.
      </p>

      <h2>6. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, {PRODUCT_NAME} and its operators
        are not liable for any indirect, incidental, special, consequential, or
        punitive damages arising out of or related to your use of the service.
      </p>

      <h2>7. Contact</h2>
      <p>
        Questions about this disclaimer? Email{" "}
        <a href={`mailto:${LEGAL_CONTACTS.legal}`}>{LEGAL_CONTACTS.legal}</a>.
      </p>
    </article>
  );
}
